# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3e4dced4e35e62821ce764fb8e55c06"
name = "subscription-tracker"
handle = "subscription-tracker-1"
application_url = "https://seryni-strack.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_app_proxy,read_customers,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_product_listings,read_products,write_app_proxy,write_customers,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = ["https://seryni-strack.onrender.com/auth/callback", "https://seryni-strack.onrender.com/auth/shopify/callback", "https://seryni-strack.onrender.com/api/auth/callback"]

[pos]
embedded = false
